### ISSUE TITLE
interpration of the outputs

### ISSUE THREAD

**Issue by maque4004** [biocore/mmvec#120]
Dear Jamie,

I have two questions, I am wondering if you can give some suggestions.
1. My data contain 10 kinds of metabolites and 2000+ microbes,  when I run mmvec commands, I used metabolite table as microbe table, and microbe table as metabolite table. so in the biplot emperor plot, each dot represents a microbe,  each arrow represents a metabolite. 
![image](https://user-images.githubusercontent.com/45165322/73718957-e3a29a80-4758-11ea-9c47-178b226d5292.png)
From the figure above, I can only tell the left arrows(metabolites) are negtively correlated with the right ones,  I may missed some important information, could you kindly help interpret the results? It's gonna help a lot.

2. And I have some issues about the parameters of qiime mmvec paired-heatmap command.
(1) I want the paired heatmap show all the samples, so I passed --p-no-keep-top-samples, but raised an error local variable 'select_microbes' referenced before assignment. I don't know what's wrong here, Below are the codes
`qiime mmvec paired-heatmap --i-ranks ranks.qza --i-microbes-table otu-table-raw.qza --i-metabolites-table  fecal-scfa.qza  --o-visualization ranks-filter-paired-heatmap-.qzv --p-normalize rel_row --p-top-k-microbes 0 --p-features <feature1> --p-features <feature2> --m-microbe-metadata-file taxonomy.txt --m-microbe-metadata-column taxa --p-no-keep-top-samples`
(2) --p-features, can I pass multiple features at once? I've tried --p-features <feature1,feature2>, it didn't work but raised an error said features must represent feature IDs in microbes_table, obviously it took <feature1,feature2> as one feature.
(3) --p-row-center, center conditional probability table around average row, I don't understand how it works.

Sorry, too many questions, thank you very much for all your help!

Best,
Yichen

**Comment by mortonjt** [comment]
1. I prefer not to use the term negative correlation (since we can't actually do correlation on relative abundance data).  It is better to say low co-occurrence probability, if the arrows are pointing in opposite direction, that it is indicative that we often don't observe those two metabolites together often.  We cannot make any statements about causality or correlation here.

2. I'm not exactly sure what is going on with the `paired-heatmap`, note that this was designed to pull out metabolites from microbes.  Since you flipped your analysis, that could be breaking things.  CC @nbokulich .

Regarding `--p-features`, yes you can pass in multiple features at once.  You just need to specify --p-features multiple times (i.e. `--p-features feature1 --p-features feature2`.  This should be in the README.

3. We perform a double centering (i.e. compute the row averages and subtract them from each other, then compute the column averages and subtract those from each column).  This is the same procedure that is done for PCA and can help with visualizing the heatmap.

Questions are good - feel free to post more :)

**Comment by nbokulich** [comment]
RE: paired heatmap thanks for reporting @maque4004 , this appears to be a bug, but using --p-keep-top-samples will fix this... I realize that's not what you want, but it is the only quick workaround right now.

I will raise this in a separate issue.

**Comment by maque4004** [comment]
Thank you very much!

@mortonjt Jamie,  back to question one, expcet the low co-occurance, can you get extra imformation from the figure?

**Comment by maque4004** [comment]
Thank you both for the reply!

@mortonjt  This is the biplot.qzv file, can you get extra imformation from the plot except the low co-occurrence?
[biplot.zip](https://github.com/biocore/mmvec/files/4173939/biplot.zip)

**Comment by mortonjt** [comment]
Could you elaborate on what you mean by extra information?

There are other visualizations / plots that can help extract
more information (see README)

**Comment by maque4004** [comment]
From the biplot.qzv, I can only infer arrows in opposite directions are less likely to exist at the same time, but cannot get other relations between the metabolites and microbes, I am wondering if you could help read more from the biplot?

**Comment by mortonjt** [comment]
Gotcha.  Arrows that are pointing in the same direction are metabolites that are likely to co-occur within the same samples.  The arrows can explain variation in the samples, so the arrows parallel to PC1 here can help differentiate microbes (this plot is hard to see that - so I'd refer to the CF biplot in the paper and in the README).

The biplot is meant to give high level information - which you need to complement with additional analysis such as differential abundance or comparative genomics.
