### ISSUE TITLE
Exact parameters used in paper

### ISSUE THREAD

**Issue by isisannelie** [biocore/mmvec#134]
Hi!

I want to see if I can reproduce your results from the paper, therefore, I was wondering what the exact parameters are that you used for the mmvec runs for the benchmarking and ihmp study. I looked through all the files in the multiomic-occurrences github, but I couldn't find any documentation on which parameters exactly were used to obtain the best model.

Thanks in advance!

**Comment by mortonjt** [comment]
@isisannelie this is a little embarrassing, looks like those scripts were accidentally left out.

I've created a pull request here: https://github.com/knightlab-analyses/multiomic-cooccurrences/pull/15
We'll need first make sure that paths match up before merging. 

For future reference, we'll want to have all benchmark related issues on the multiomics-cooccurrence repository so that we keep the mmvec features / bugs separate from reproducing the manuscript results.

**Comment by mortonjt** [comment]
Hi @isisannelie, I've merged in the missing scripts in the [multiomic-co-occurrences](https://github.com/knightlab-analyses/multiomic-cooccurrences) repository. Thank you for bringing this to our attention, please feel free to raise more issues on that repository if you run into any additional problems.
