### ISSUE TITLE
doubt in generating a heatmap

### ISSUE THREAD

**Issue by khemlalnirmalkar** [biocore/mmvec#137]
Hi @mortonjt 

I am interested in making some figures like in your mmvec paper's (Morton et al., 2019, Nature Methods) figures 6a and 6b. (couldn't attach the figure here), where i can show the relation between microbe and metabolites. But i could find scripts/command in the tutorial for that kind of figure.
Is it there in the tutorial but I missed it or do i need to make it manually? please can you guide in this step?
Thanks,
Khem

**Comment by mortonjt** [comment]
There are python notebooks to do this here:
https://github.com/knightlab-analyses/multiomic-cooccurrences/blob/master/ipynb/Figure6-inflammatory-bowel-disease.ipynb

**Comment by khemlalnirmalkar** [comment]
Thank you for your immediate response @mortonjt .
I will check it the link now.
Khem

**Comment by LiZhihua1982** [comment]
Hi Jamie,
    Would you make more details such as how to obtain the result of  mmvec_dir and songbird_dir? Because I use the pipeline of Qiime2 plugin in the https://github.com/biocore/mmvec/.  I do not know how to get the corresponding results as above. Thank you very much!

Best regards

Li Zhihua

**Comment by mortonjt** [comment]
I'm not sure if I understand the question. If you want to run qiime2 songbird, see the [songbird readme](https://github.com/biocore/songbird).  The manuscript results were not created using the qiime2 plugin.

If you want to combine the songbird / mmvec results, you can view them jointly through the biplot command
```
qiime emperor biplot \
        --i-biplot conditional_biplot.qza \
        --m-sample-metadata-file <your metabolite songbird results> \
        --m-feature-metadata-file <your microbe songbird results> \
        --o-visualization emperor.qzv
```

Since this question was originally about generating heatmaps, I'm going to close this issue.  Feel free to follow up if there are specific questions.
