### ISSUE TITLE
Could mmvec measure the consumption of metabolites?

### ISSUE THREAD

**Issue by wanglu2014** [biocore/mmvec#163]
There is no comparison on the consumption of metabolites in your paper. Did the negative mmvec value of a metabolites for a microbe directly suggest that the microbe consumed this metabolite?

**Comment by mortonjt** [comment]
Negative values likely correspond to low co-occurrence probabilities.

So no, they wouldn't correspond to consumption, since you have both the microbe / molecule present, it would actually be a positive co-occurrence. Do note that getting consumption rates from sequencing / mass-spec data is not currently possible with MMvec -- you'd need longitudinal data + absolute abundances and another tool that can incorporate all of this.
